<script setup lang="ts">
const updateTitle = (newTitle: string) => {
  document.title = newTitle;
};
import { onMounted } from 'vue';
onMounted(() => {
  updateTitle('Termes & Conditions');
});
</script>

<template>
    <div class="mx-4">
        <h1 class="font-lalezar pt-4 pb-2 text-2xl font-bold">TERMES & CONDITIONS</h1>
        <p>1. CATÉGORIES DE DONNÉES À CARACTÈRE PERSONNEL
1.1 Données d’abonnement
En adhérant à Squard en tant que membre, vous aurez la possibilité de souscrire à un contrat d'abonnement. Afin de vous offrir nos services, nous sommes tenus de traiter certaines données personnelles que vous nous communiquez lors du processus d'abonnement. Ces informations incluent votre nom, votre adresse personnelle, votre numéro de téléphone, votre adresse e-mail, votre numéro de compte bancaire, votre genre et votre date de naissance. À la suite de cela, nous vous attribuerons un numéro d'abonnement ainsi qu'un numéro de passe Squard.
1.2 Squard
Squard propose à ses membres un espace en ligne où ils peuvent accéder à leurs données personnelles et aux informations relatives à leur abonnement en se connectant avec leur mot de passe. Les informations présentes dans la section "Mon Compte" reflètent les données enregistrées dans notre système de gestion des abonnements. Vous avez la possibilité de vous connecter soit via le site web Squard, soit via l'application Squard. De plus, vous avez la liberté d'ajuster certaines données ou paramètres à tout moment de manière autonome.
1.3 Application Spate
Notre application vise à accompagner nos membres dans leur parcours sportif en mettant à leur disposition un outil en libre-service pour gérer leur abonnement et rester informés de nos services. La plupart des données présentées dans l'application proviennent de votre compte. Après avoir activé votre compte, vous avez la possibilité de personnaliser l'application selon vos propres objectifs et centres d'intérêt. Si vous préférez ne pas personnaliser l'application, vous pouvez simplement ignorer ces questions. Les catégories de données personnelles que nous distinguons dans notre application sont les suivantes : Données pour la création d'un compte et l'utilisation de l'application : En tant que membre de Squard, vous pouvez installer et vous connecter à l'application en fournissant vos identifiants d'abonnement, rendant ainsi vos données d'abonnement automatiquement visibles dans l'application. Données pour atteindre vos objectifs sportifs et personnaliser votre application : Si vous le souhaitez, notre application peut vous aider à atteindre vos objectifs sportifs. Vous avez la possibilité d'ajouter des informations telles que votre taille, votre poids, vos objectifs, vos aspirations, vos centres d'intérêt, vos préférences sportives, ainsi que vos séances d'entraînement programmées et complétées.
1.4. Données analytiques
Nous examinons l'utilisation de l'application dans le but d'améliorer sa fonctionnalité et sa sécurité, ainsi que pour des aspects de personnalisation et de marketing. Cette analyse est effectuée à l'aide d'un identifiant unique, exclusivement compréhensible par Squard, et aucune donnée d'utilisateur ou d'appareil n'est utilisée à cette fin. Squard recourt à l'analytique de Google et établit un contrat de traitement des données avec Google à cet égard. Google utilise des données d'appareil, telles que le numéro IMEI, à des fins d'identification.
1.5 Critères de Conservation
Nous conservons vos données personnelles aussi longtemps que nécessaire pour respecter nos obligations légales, réglementaires, fiscales, de gestion des litiges et pour nous conformer à nos engagements contractuels. Si nous n'avons plus besoin de vos données personnelles à des fins spécifiques, elles seront supprimées ou anonymisées.
1.6 Demande de Suppression
Vous avez le droit de demander la suppression de vos données personnelles à tout moment. Nous répondrons à ces demandes dans les délais prescrits par la loi, sous réserve de la conservation nécessaire des données à des fins légales ou contractuelles.
2. Sécurité de l’application
Les données de l'application ainsi que les informations personnalisées provenant de l'Analyseur corporel sont stockées de manière pseudonymisée dans une base de données sécurisée distincte. Cette base de données ne renferme en elle-même aucune information permettant d'identifier un individu. Ces données ne sont pas enregistrées dans notre système de gestion des membres et demeurent exclusivement visibles par l'utilisateur de l'application sur son propre appareil. Toutes les transmissions de données relatives à l'application sont sécurisées grâce à des techniques de chiffrement.
Lors du processus d'abonnement, vous avez la possibilité de définir vos préférences en matière de marketing. Tout au long de votre abonnement chez Squard, vous pouvez ajuster ces paramètres à tout moment via l'application Squard ou en suivant le lien de désinscription fourni dans nos communications. En fonction de vos choix et réglages, Squard peut vous envoyer des e-mails, des SMS ou des notifications via l'application. En ce qui concerne les informations nécessaires à l'abonnement, au club de référence, aux tarifs, etc., nous ne communiquons pas sur la base du consentement, mais plutôt en vertu de la bonne exécution du contrat avec nos membres et de l'importance de ces informations pour certaines questions. Pour les besoins de marketing et de communication, Squard utilise les données personnelles pour cibler correctement des groupes spécifiques, tels que le club de référence, le pays, la région, etc. Il est important de noter que Squard n'utilise pas le profilage conduisant à des prises de décision automatisées.
2.1 Marketing, ventes et communication

2.2 Enquêtes
De temps à autre, nous sollicitons la participation de nos membres à des enquêtes dans le but d'améliorer nos services. Cette démarche est toujours volontaire et ne se déroule qu'avec le consentement explicite du membre. Nous précisons également clairement à l'avance si l'enquête est anonyme ou non.
2.3 Problèmes de paiement
En cas de non-paiement des frais d'abonnement par un membre, des rappels de paiement sont initialement envoyés par e-mail. En l'absence de réponse, un rappel est envoyé par SMS au numéro de téléphone fourni par le membre. À ce stade, l'agence de collecte devient le "responsable du traitement des données" pour les informations que nous leur transmettons, afin de gérer ultérieurement le cas. Ces données seront traitées et conservées en conformité avec les procédures et réglementations applicables auxquelles les agences de collecte sont soumises.
2.4 Réseaux sociaux
Squard utilise les réseaux sociaux tels que Facebook, Twitter et Instagram en disposant de sa propre page de profil. À travers ces canaux, vous pouvez suivre Squard et interagir avec nos communications et flux d'informations. Pour ces interactions, la politique de confidentialité de la plateforme respective s'applique. Si vous avez des questions ou des problèmes liés à votre abonnement, vous pouvez également nous contacter via notre service de messages privés après avoir été identifié en tant que membre de notre communauté. Ces messages privés seront gérés par notre service client ou nos experts en marketing au sein de notre système de membres dédié. Cela signifie que toutes nos communications à travers différents canaux sont centralisées dans notre système de membres. Les informations relatives à votre abonnement seront partagées uniquement par le biais de la messagerie privée et jamais par la messagerie publique.
2.5 Analyse et recherche (de marché)
Squard n'utilise que des données agrégées et anonymisées lorsqu'il s'agit d'analyses statistiques, de rapports de gestion et d'activités de recherche de marché. Pour le contenu marketing, nous pouvons cibler certains groupes en utilisant des données telles que le pays, la région, le club favori et le type d'abonnement. Notre objectif est de veiller à ce que nos membres reçoivent du contenu correspondant à leurs préférences, tout en préservant leur confidentialité grâce à l'utilisation de données agrégées et anonymes.
2.6 Site Web et cookies
La déclaration sur les cookies de Squard, disponible sur notre site Web, fournit des informations détaillées sur les types de cookies que nous utilisons. Lorsque vous ouvrez notre site, une bannière de cookies apparaît, vous permettant de définir vos propres paramètres. Par défaut, seuls les cookies fonctionnels nécessaires sont activés. Vous avez la possibilité de personnaliser vos préférences en matière de cookies grâce à cette bannière.
2.7 Consentement Révocable
Votre consentement à l'utilisation de cookies est révocable à tout moment. Si vous changez d'avis concernant notre politique de cookies, vous pouvez mettre à jour vos préférences en matière de cookies ou retirer votre consentement en suivant les instructions fournies dans les paramètres de votre navigateur.
3. QUELLES SONT NOS BASES JURIDIQUES ET LES FINALITÉS DU TRAITEMENT ?
Nous ne traitons vos données personnelles que sur la base d'une justification légale, conformément à l'article 6 du RGPD. Nous nous appuyons sur les principes suivants : Données nécessaires au contrat d'abonnement et aux services proposés : La base légale est définie par l'article 6(1)(b) du RGPD, indiquant que le traitement est nécessaire à l'exécution d'un contrat. Ces données sont essentielles pour gérer votre abonnement et fournir nos services. Données supplémentaires pour créer un profil de fitness personnalisé : Les informations telles que votre taille, votre poids, votre IMC, vos objectifs de fitness, et vos centres d'intérêt sont collectées dans le but de créer un profil de fitness personnalisé. La base légale repose sur l'article 6(1)(a) du RGPD, ce qui signifie que le traitement est effectué avec votre consentement. Vous avez la possibilité d'ignorer ces questions lors de l'installation de l'application Squard ou de supprimer ces données vous-même. Activités de marketing et de vente pour nos produits et services : La base légale est établie par l'article 6(1)(f) du RGPD, qui se réfère aux intérêts légitimes du responsable du traitement. Nous offrons toujours la possibilité de vous désabonner pendant le processus d'abonnement ou à tout moment via l'application Squard et les liens de désinscription dans nos communications. Activités de marketing et de vente liées à nos partenaires et tiers : La base légale repose sur l'article 6(1)(a) du RGPD, indiquant que le traitement est effectué avec votre consentement. Ces paramètres sont facultatifs par défaut, et vous avez la possibilité de les activer vous-même lors de votre abonnement via l'application Squard.
4. COMMENT PROTÉGEONS-NOUS VOS DONNÉES ?
Squard met en place des mesures appropriées pour garantir la protection des données personnelles contre toute perte, accès non autorisé, altération ou tout autre traitement illégal. Ces mesures sont mises en œuvre à travers des approches physiques, techniques et organisationnelles adaptées, variées en fonction des systèmes ou de la collecte de données, et tenant compte des risques spécifiques associés. Par exemple, le transfert de données entre le site Web et l'application Squard est chiffré. Sur le plan organisationnel, nous disposons d'un système de gestion de la sécurité de l'information, d'un cadre de contrôle interne et d'un programme de conformité au RGPD. En outre, nous réalisons régulièrement des évaluations des risques, des tests de sécurité, des tests de pénétration et des audits pour assurer la robustesse de nos mesures de sécurité.
5. CONSERVATION DES DONNÉES
En cas de réclamation concernant votre vie privée, nous vous encourageons à contacter d'abord le délégué à la protection des données de Squard. Si vous estimez que votre réclamation n'est pas traitée de manière satisfaisante, vous avez également le droit de déposer une réclamation auprès de l'autorité de contrôle pour la protection des données en France.
6. PLAINTES – AUTORITÉS DE PROTECTION DES DONNÉES
Les données de votre application Squard seront automatiquement supprimées deux mois après la désinstallation de l'application sur votre appareil. Toutefois, les données liées aux paiements d'abonnements seront conservées plus longtemps conformément à la législation fiscale nationale. Ces données sont stockées sous forme pseudonymisée et ne peuvent être utilisées à aucune autre fin que celle exigée par la réglementation fiscale.</p>
</div>
</template>